name: Create release and upload asset

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Release and Upload Asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Get the version
      id: get_version
      run: |
        REV_COUNT=`git rev-list --count HEAD`
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - uses: gradle/gradle-build-action@v3
      name: Setup Gradle
      id: setup-gradle
    - name: Build and check
      run: ./gradlew -PenvIsCi=true build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/deepl-connector-plugin-${{ steps.get_version.outputs.VERSION }}.jar
        tag: ${{ github.ref }}
        overwrite: true
